//
// ! \file idssschema.proto
// ! \brief A file that contains the protocol buffer definition for the messages that are exchanged between the nodes in the network.
//
// Copyright 2023-2027, University of Salento, Italy.
// All rights reserved.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v4.25.3
// source: idssschema.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_QUERY                 MessageType = 0
	MessageType_RESULT                MessageType = 1
	MessageType_CUSTOMER_REGISTRATION MessageType = 2
	MessageType_SETTLEMENT_REQUEST    MessageType = 3
	MessageType_SETTLEMENT_RESULT     MessageType = 4
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "QUERY",
		1: "RESULT",
		2: "CUSTOMER_REGISTRATION",
		3: "SETTLEMENT_REQUEST",
		4: "SETTLEMENT_RESULT",
	}
	MessageType_value = map[string]int32{
		"QUERY":                 0,
		"RESULT":                1,
		"CUSTOMER_REGISTRATION": 2,
		"SETTLEMENT_REQUEST":    3,
		"SETTLEMENT_RESULT":     4,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_idssschema_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_idssschema_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_idssschema_proto_rawDescGZIP(), []int{0}
}

type QueryState_State int32

const (
	QueryState_QUEUED           QueryState_State = 0 // The query is in the queue
	QueryState_LOCALLY_EXECUTED QueryState_State = 1 // The query is executed locally
	QueryState_COMPLETED        QueryState_State = 2 // The query is completed
	QueryState_SENT_BACK        QueryState_State = 3 // Query result is sent back to the parent node
	QueryState_FAILED           QueryState_State = 4 // The query failed
)

// Enum value maps for QueryState_State.
var (
	QueryState_State_name = map[int32]string{
		0: "QUEUED",
		1: "LOCALLY_EXECUTED",
		2: "COMPLETED",
		3: "SENT_BACK",
		4: "FAILED",
	}
	QueryState_State_value = map[string]int32{
		"QUEUED":           0,
		"LOCALLY_EXECUTED": 1,
		"COMPLETED":        2,
		"SENT_BACK":        3,
		"FAILED":           4,
	}
)

func (x QueryState_State) Enum() *QueryState_State {
	p := new(QueryState_State)
	*p = x
	return p
}

func (x QueryState_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueryState_State) Descriptor() protoreflect.EnumDescriptor {
	return file_idssschema_proto_enumTypes[1].Descriptor()
}

func (QueryState_State) Type() protoreflect.EnumType {
	return &file_idssschema_proto_enumTypes[1]
}

func (x QueryState_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueryState_State.Descriptor instead.
func (QueryState_State) EnumDescriptor() ([]byte, []int) {
	return file_idssschema_proto_rawDescGZIP(), []int{4, 0}
}

// QueryMessage represents a query being propagated in the network
type QueryMessage struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Type                 MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=common.MessageType" json:"type,omitempty"`                // To distinguish between QUERY and RESULT.
	Query                string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`                                       // The query to be executed
	Uqid                 string                 `protobuf:"bytes,3,opt,name=uqid,proto3" json:"uqid,omitempty"`                                         // Unique query identifier
	Timestamp            string                 `protobuf:"bytes,11,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                              // Timestamp of the query
	Ttl                  float32                `protobuf:"fixed32,4,opt,name=ttl,proto3" json:"ttl,omitempty"`                                         // Time to live
	Sender               string                 `protobuf:"bytes,5,opt,name=sender,proto3" json:"sender,omitempty"`                                     // The peer_id of the sender
	Originator           string                 `protobuf:"bytes,6,opt,name=originator,proto3" json:"originator,omitempty"`                             // The peer_id of the originator
	State                *QueryState            `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`                                       // The state of the query
	Labels               []string               `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty"`                                     // The labels of the query
	Result               []*Row                 `protobuf:"bytes,9,rep,name=result,proto3" json:"result,omitempty"`                                     // The result of the query
	Error                string                 `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`                                      // Error message if any
	RecordCount          int32                  `protobuf:"varint,12,opt,name=record_count,json=recordCount,proto3" json:"record_count,omitempty"`      // Number of records in the result
	RequesterId          string                 `protobuf:"bytes,13,opt,name=requester_id,json=requesterId,proto3" json:"requester_id,omitempty"`       // Peer ID of the submitting client
	RequesterRole        string                 `protobuf:"bytes,14,opt,name=requester_role,json=requesterRole,proto3" json:"requester_role,omitempty"` // member, manager, or observer
	CustomerRegistration *CustomerRegistration  `protobuf:"bytes,15,opt,name=customer_registration,json=customerRegistration,proto3" json:"customer_registration,omitempty"`
	SettlementRequest    *SettlementRequest     `protobuf:"bytes,16,opt,name=settlement_request,json=settlementRequest,proto3" json:"settlement_request,omitempty"`
	SettlementResult     *SettlementResult      `protobuf:"bytes,17,opt,name=settlement_result,json=settlementResult,proto3" json:"settlement_result,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *QueryMessage) Reset() {
	*x = QueryMessage{}
	mi := &file_idssschema_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryMessage) ProtoMessage() {}

func (x *QueryMessage) ProtoReflect() protoreflect.Message {
	mi := &file_idssschema_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryMessage.ProtoReflect.Descriptor instead.
func (*QueryMessage) Descriptor() ([]byte, []int) {
	return file_idssschema_proto_rawDescGZIP(), []int{0}
}

func (x *QueryMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_QUERY
}

func (x *QueryMessage) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryMessage) GetUqid() string {
	if x != nil {
		return x.Uqid
	}
	return ""
}

func (x *QueryMessage) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *QueryMessage) GetTtl() float32 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *QueryMessage) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *QueryMessage) GetOriginator() string {
	if x != nil {
		return x.Originator
	}
	return ""
}

func (x *QueryMessage) GetState() *QueryState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *QueryMessage) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *QueryMessage) GetResult() []*Row {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *QueryMessage) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *QueryMessage) GetRecordCount() int32 {
	if x != nil {
		return x.RecordCount
	}
	return 0
}

func (x *QueryMessage) GetRequesterId() string {
	if x != nil {
		return x.RequesterId
	}
	return ""
}

func (x *QueryMessage) GetRequesterRole() string {
	if x != nil {
		return x.RequesterRole
	}
	return ""
}

func (x *QueryMessage) GetCustomerRegistration() *CustomerRegistration {
	if x != nil {
		return x.CustomerRegistration
	}
	return nil
}

func (x *QueryMessage) GetSettlementRequest() *SettlementRequest {
	if x != nil {
		return x.SettlementRequest
	}
	return nil
}

func (x *QueryMessage) GetSettlementResult() *SettlementResult {
	if x != nil {
		return x.SettlementResult
	}
	return nil
}

type CustomerRegistration struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Mrid             string                 `protobuf:"bytes,1,opt,name=mrid,proto3" json:"mrid,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Role             string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	MembershipStatus string                 `protobuf:"bytes,4,opt,name=membership_status,json=membershipStatus,proto3" json:"membership_status,omitempty"`
	ContractNumber   string                 `protobuf:"bytes,5,opt,name=contract_number,json=contractNumber,proto3" json:"contract_number,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CustomerRegistration) Reset() {
	*x = CustomerRegistration{}
	mi := &file_idssschema_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerRegistration) ProtoMessage() {}

func (x *CustomerRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_idssschema_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerRegistration.ProtoReflect.Descriptor instead.
func (*CustomerRegistration) Descriptor() ([]byte, []int) {
	return file_idssschema_proto_rawDescGZIP(), []int{1}
}

func (x *CustomerRegistration) GetMrid() string {
	if x != nil {
		return x.Mrid
	}
	return ""
}

func (x *CustomerRegistration) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CustomerRegistration) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CustomerRegistration) GetMembershipStatus() string {
	if x != nil {
		return x.MembershipStatus
	}
	return ""
}

func (x *CustomerRegistration) GetContractNumber() string {
	if x != nil {
		return x.ContractNumber
	}
	return ""
}

type SettlementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettlementRequest) Reset() {
	*x = SettlementRequest{}
	mi := &file_idssschema_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettlementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettlementRequest) ProtoMessage() {}

func (x *SettlementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idssschema_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettlementRequest.ProtoReflect.Descriptor instead.
func (*SettlementRequest) Descriptor() ([]byte, []int) {
	return file_idssschema_proto_rawDescGZIP(), []int{2}
}

func (x *SettlementRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *SettlementRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type SettlementResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PeerId          string                 `protobuf:"bytes,1,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	MeterReadingSum float64                `protobuf:"fixed64,2,opt,name=meter_reading_sum,json=meterReadingSum,proto3" json:"meter_reading_sum,omitempty"`
	TradeVolumeSum  float64                `protobuf:"fixed64,3,opt,name=trade_volume_sum,json=tradeVolumeSum,proto3" json:"trade_volume_sum,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SettlementResult) Reset() {
	*x = SettlementResult{}
	mi := &file_idssschema_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettlementResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettlementResult) ProtoMessage() {}

func (x *SettlementResult) ProtoReflect() protoreflect.Message {
	mi := &file_idssschema_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettlementResult.ProtoReflect.Descriptor instead.
func (*SettlementResult) Descriptor() ([]byte, []int) {
	return file_idssschema_proto_rawDescGZIP(), []int{3}
}

func (x *SettlementResult) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *SettlementResult) GetMeterReadingSum() float64 {
	if x != nil {
		return x.MeterReadingSum
	}
	return 0
}

func (x *SettlementResult) GetTradeVolumeSum() float64 {
	if x != nil {
		return x.TradeVolumeSum
	}
	return 0
}

type QueryState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         QueryState_State       `protobuf:"varint,1,opt,name=state,proto3,enum=common.QueryState_State" json:"state,omitempty"`
	Result        []*Row                 `protobuf:"bytes,2,rep,name=result,proto3" json:"result,omitempty"` // Optional, to store intermediate/final results if needed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryState) Reset() {
	*x = QueryState{}
	mi := &file_idssschema_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryState) ProtoMessage() {}

func (x *QueryState) ProtoReflect() protoreflect.Message {
	mi := &file_idssschema_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryState.ProtoReflect.Descriptor instead.
func (*QueryState) Descriptor() ([]byte, []int) {
	return file_idssschema_proto_rawDescGZIP(), []int{4}
}

func (x *QueryState) GetState() QueryState_State {
	if x != nil {
		return x.State
	}
	return QueryState_QUEUED
}

func (x *QueryState) GetResult() []*Row {
	if x != nil {
		return x.Result
	}
	return nil
}

// Row represents a single row in the query result
type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []string               `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_idssschema_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_idssschema_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_idssschema_proto_rawDescGZIP(), []int{5}
}

func (x *Row) GetData() []string {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_idssschema_proto protoreflect.FileDescriptor

var file_idssschema_proto_rawDesc = string([]byte{
	0x0a, 0x10, 0x69, 0x64, 0x73, 0x73, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x22, 0x97, 0x05, 0x0a, 0x0c, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x27, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x71,
	0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x71, 0x69, 0x64, 0x12, 0x1c,
	0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x10, 0x0a, 0x03,
	0x74, 0x74, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x74, 0x74, 0x6c, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e,
	0x61, 0x74, 0x6f, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x72, 0x69, 0x67,
	0x69, 0x6e, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x28, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x12, 0x23, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x52, 0x6f, 0x77, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x72, 0x65, 0x63, 0x6f, 0x72,
	0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65,
	0x12, 0x51, 0x0a, 0x15, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x72, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65,
	0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x14, 0x63,
	0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x48, 0x0a, 0x12, 0x73, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x10, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x11, 0x73, 0x65, 0x74, 0x74,
	0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x45, 0x0a,
	0x11, 0x73, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x18, 0x11, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x52, 0x10, 0x73, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0xa8, 0x01, 0x0a, 0x14, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65,
	0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a,
	0x04, 0x6d, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x72, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x2b, 0x0a, 0x11, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x68, 0x69, 0x70,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22,
	0x37, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x22, 0x81, 0x01, 0x0a, 0x10, 0x53, 0x65, 0x74,
	0x74, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x70, 0x65, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x11, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x5f,
	0x72, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x0f, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x52, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x53,
	0x75, 0x6d, 0x12, 0x28, 0x0a, 0x10, 0x74, 0x72, 0x61, 0x64, 0x65, 0x5f, 0x76, 0x6f, 0x6c, 0x75,
	0x6d, 0x65, 0x5f, 0x73, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0e, 0x74, 0x72,
	0x61, 0x64, 0x65, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x53, 0x75, 0x6d, 0x22, 0xb6, 0x01, 0x0a,
	0x0a, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x2e, 0x0a, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x53, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x23, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x6f, 0x77, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x22, 0x53, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x51, 0x55, 0x45,
	0x55, 0x45, 0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x4c, 0x4f, 0x43, 0x41, 0x4c, 0x4c, 0x59,
	0x5f, 0x45, 0x58, 0x45, 0x43, 0x55, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x43,
	0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x45,
	0x4e, 0x54, 0x5f, 0x42, 0x41, 0x43, 0x4b, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x41, 0x49,
	0x4c, 0x45, 0x44, 0x10, 0x04, 0x22, 0x19, 0x0a, 0x03, 0x52, 0x6f, 0x77, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x2a, 0x6e, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x09, 0x0a, 0x05, 0x51, 0x55, 0x45, 0x52, 0x59, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x45,
	0x53, 0x55, 0x4c, 0x54, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15, 0x43, 0x55, 0x53, 0x54, 0x4f, 0x4d,
	0x45, 0x52, 0x5f, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10,
	0x02, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x45, 0x54, 0x54, 0x4c, 0x45, 0x4d, 0x45, 0x4e, 0x54, 0x5f,
	0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x10, 0x03, 0x12, 0x15, 0x0a, 0x11, 0x53, 0x45, 0x54,
	0x54, 0x4c, 0x45, 0x4d, 0x45, 0x4e, 0x54, 0x5f, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x10, 0x04,
	0x42, 0x15, 0x5a, 0x13, 0x69, 0x64, 0x73, 0x73, 0x2f, 0x67, 0x72, 0x61, 0x70, 0x68, 0x64, 0x62,
	0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_idssschema_proto_rawDescOnce sync.Once
	file_idssschema_proto_rawDescData []byte
)

func file_idssschema_proto_rawDescGZIP() []byte {
	file_idssschema_proto_rawDescOnce.Do(func() {
		file_idssschema_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_idssschema_proto_rawDesc), len(file_idssschema_proto_rawDesc)))
	})
	return file_idssschema_proto_rawDescData
}

var file_idssschema_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_idssschema_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_idssschema_proto_goTypes = []any{
	(MessageType)(0),             // 0: common.MessageType
	(QueryState_State)(0),        // 1: common.QueryState.State
	(*QueryMessage)(nil),         // 2: common.QueryMessage
	(*CustomerRegistration)(nil), // 3: common.CustomerRegistration
	(*SettlementRequest)(nil),    // 4: common.SettlementRequest
	(*SettlementResult)(nil),     // 5: common.SettlementResult
	(*QueryState)(nil),           // 6: common.QueryState
	(*Row)(nil),                  // 7: common.Row
}
var file_idssschema_proto_depIdxs = []int32{
	0, // 0: common.QueryMessage.type:type_name -> common.MessageType
	6, // 1: common.QueryMessage.state:type_name -> common.QueryState
	7, // 2: common.QueryMessage.result:type_name -> common.Row
	3, // 3: common.QueryMessage.customer_registration:type_name -> common.CustomerRegistration
	4, // 4: common.QueryMessage.settlement_request:type_name -> common.SettlementRequest
	5, // 5: common.QueryMessage.settlement_result:type_name -> common.SettlementResult
	1, // 6: common.QueryState.state:type_name -> common.QueryState.State
	7, // 7: common.QueryState.result:type_name -> common.Row
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_idssschema_proto_init() }
func file_idssschema_proto_init() {
	if File_idssschema_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_idssschema_proto_rawDesc), len(file_idssschema_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_idssschema_proto_goTypes,
		DependencyIndexes: file_idssschema_proto_depIdxs,
		EnumInfos:         file_idssschema_proto_enumTypes,
		MessageInfos:      file_idssschema_proto_msgTypes,
	}.Build()
	File_idssschema_proto = out.File
	file_idssschema_proto_goTypes = nil
	file_idssschema_proto_depIdxs = nil
}
